plugins/request/src/main/resources/META-INF/cxs/actions/requestHeaderToProfilePropertyAction.json
=> Error in log files while starting unomi 1.1.0

api/src/main/java/org/apache/unomi/api/PersonaWithSessions.java, api/src/main/java/org/apache/unomi/api/services/ProfileService.java, rest/src/main/java/org/apache/unomi/rest/ProfileServiceEndPoint.java, services/src/main/java/org/apache/unomi/services/services/ProfileServiceImpl.java
Implemented the ability to save a personaWithSession object via UNOMI API.
=> UNOMI-79 : Implement save persona with sessions.

api/src/main/java/org/apache/unomi/api/ContextRequest.java, src/site/markdown/versions/1.1/getting-started.md, src/site/markdown/versions/master/getting-started.md, wab/src/main/java/org/apache/unomi/web/ContextServlet.java
Implement overrides for scores and put segments,scores and profileproperties in the same object (Profile object)
=> UNOMI-86 : Implements overrides for scores

extensions/weather-update/.gitignore, extensions/weather-update/README.md, extensions/weather-update/core/pom.xml, extensions/weather-update/core/src/main/java/org/apache/unomi/weatherupdate/actions/WeatherUpdateAction.java, extensions/weather-update/core/src/main/resources/META-INF/cxs/actions/UpdateWeatherAction.json, extensions/weather-update/core/src/main/resources/META-INF/cxs/properties/sessions/weather/weatherLike.json, extensions/weather-update/core/src/main/resources/META-INF/cxs/properties/sessions/weather/weatherTemp.json, extensions/weather-update/core/src/main/resources/META-INF/cxs/properties/sessions/weather/weatherWindDirection.json, extensions/weather-update/core/src/main/resources/META-INF/cxs/properties/sessions/weather/weatherWindSpeed.json, extensions/weather-update/core/src/main/resources/META-INF/cxs/rules/UpdateWeather.json, extensions/weather-update/core/src/main/resources/META-INF/cxs/tags/properties/sessions/weatherSessionProperties.json, extensions/weather-update/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, extensions/weather-update/core/src/main/resources/messages_en.properties, extensions/weather-update/core/src/main/resources/org.apache.unomi.weatherUpdate.cfg, extensions/weather-update/karaf-kar/pom.xml, extensions/weather-update/karaf-kar/src/main/feature/feature.xml, extensions/weather-update/pom.xml, persistence-elasticsearch/core/src/main/resources/org.apache.unomi.persistence.elasticsearch.cfg
Add new extension update Session with weather information based on user location
=> Weather update

tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/ActionListCommand.java, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/ActionViewCommand.java, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/RuleListCommand.java, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/RuleResetStatsCommand.java, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/RuleViewcommand.java, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/SegmentListCommand.java
- Consistent sorting of results by name
- Missing output to CSV
- Remove unnecessary --no-format parameter
- Various style fixes
=> UNOMI-165 Minor improvements in dev shell commands

kar/src/main/feature/feature.xml
This is a PR for fixing kar deployment in a fresh Karaf 4.2.x instance.
It's temporary before having the next major refactor for Karaf 4.x.
=> Fix Kar feature deployment in Karaf 4.2.x

tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/impl/MigrationTo121.java
Fix: [#UNOMI-224](https://issues.apache.org/jira/browse/UNOMI-224) to avoid crash of program.
=> [UNOMI-224] fix an API bug which may crash the program.

MERGING-PULL-REQUESTS, README.md, generate-site-and-upload.sh
@sergehuber this PR clean some incubator URLs
=> Clean incubator urls

itests/pom.xml, itests/src/test/java/org/apache/unomi/itests/BaseIT.java, package/pom.xml, performance-tests/pom.xml, performance-tests/src/test/java/org/apache/unomi/performancetests/BasicTest.java, plugins/request/pom.xml, plugins/request/src/main/java/org/apache/unomi/plugins/request/actions/SetRemoteHostInfoAction.java, plugins/request/src/main/java/org/apache/unomi/plugins/request/useragent/UserAgent.java, plugins/request/src/main/java/org/apache/unomi/plugins/request/useragent/UserAgentDetectorServiceImpl.java, plugins/request/src/main/resources/OSGI-INF/blueprint/blueprint.xml, plugins/request/src/test/java/org/apache/unomi/plugins/request/actions/UserAgentDetectorTest.java, pom.xml, services/pom.xml, services/src/main/resources/OSGI-INF/blueprint/blueprint.xml
@sergehuber can you review please?
All tests passed but if you have some guideline to test this more, I can make more test :)
=> [UNOMI-228] Replace user agent detector library

manual/src/main/asciidoc/5-min-quickstart.adoc, manual/src/main/asciidoc/building-and-deploying.adoc, manual/src/main/asciidoc/configuration.adoc, manual/src/main/asciidoc/consent-api.adoc, manual/src/main/asciidoc/custom-extensions.adoc, manual/src/main/asciidoc/index.adoc, manual/src/main/asciidoc/recipes.adoc, manual/src/main/asciidoc/request-examples.adoc, manual/src/main/asciidoc/samples/twitter-sample.adoc, manual/src/main/asciidoc/useful-unomi-urls.adoc
- Update git repo url
- Fix all incubator urls
=> [UNOMI-243] Can't clone repository

services/src/main/java/org/apache/unomi/services/services/GoalsServiceImpl.java
* Usage of LinkedHashSet instead of HashSet
=> UNOMI-241 improve retrieving of goals in the correct order

manual/src/main/asciidoc/recipes.adoc
I have found some issue with documentation. This pull request fix some of the issue.
=> fix typo in recipes

manual/src/main/asciidoc/shell-commands.adoc, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/DeploymentCommandSupport.java, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/EventList.java, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/EventSearch.java, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/ProfileRemove.java, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/RuleRemove.java, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/SegmentRemove.java, tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/UndeployDefinition.java
The following shell dev commands have been added:
- List events
- Search for events by profile Id and type
- Remove a profile
- Remove a rule
- Remove a segment
- View a segment
- Undeploy definitions provided by a plugin
- Added the possibility to deploy all the definitions contained in a plugin with the deploy-definition command.
Signed-off-by: Serge Huber <shuber@apache.org>
=> UNOMI-249 New shell commands to make plugin development easier

api/pom.xml, api/src/main/java/org/apache/unomi/api/actions/ActionType.java, itests/pom.xml, itests/src/test/java/org/apache/unomi/itests/BaseIT.java, kar/src/main/feature/feature.xml, package/pom.xml, performance-tests/src/test/java/org/apache/unomi/performancetests/BasicTest.java, persistence-elasticsearch/core/pom.xml, persistence-elasticsearch/pom.xml, plugins/baseplugin/pom.xml, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PropertyConditionEvaluator.java, plugins/mail/pom.xml, plugins/request/pom.xml, pom.xml, rest/pom.xml, rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml, services/src/main/java/org/apache/unomi/services/impl/definitions/DefinitionsServiceImpl.java
This PR adds support for JDK 11 for both execution and compilation.
=> UNOMI-259 JDK 11 support

services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java
Fixed UNOMI_261 - Unable to update consent status through cxs/profiles endpoint
=> Handled Enum while merging profiles

plugins/kafka-injector/pom.xml, plugins/kafka-injector/src/main/java/org/apache/unomi/kafka/KafkaInjector.java
It's not fully ready to be merged. I would like to add tests, documentation, etc. I'm working on it.
=> WIP: [UNOMI-66] Add kafka injector plugin

plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/SetPropertyAction.java, plugins/baseplugin/src/main/resources/META-INF/cxs/rules/sessionPageReferrer.json, wab/src/main/java/org/apache/unomi/web/ContextServlet.java, wab/src/main/java/org/apache/unomi/web/EventsCollectorServlet.java, wab/src/main/java/org/apache/unomi/web/ServletCommon.java
=> UNOMI-285 Make sessions optional in eventcollector and contextservlet

plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PropertyConditionEvaluator.java
Fixed using proper conversion of instant to date
=> UNOMI-329 Date comparisons don't work properly in rule conditions

services/src/main/java/org/apache/unomi/services/impl/events/EventServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java
Fixed by replacing ArrayList with CopyOnWriteList
=> UNOMI-331 Concurrency issues in rules and event listeners

pom.xml
Upgraded to version 2.4.7.Final that is compatible up to JDK 12.
=> UNOMI-333 MVEL2 JDK 11 compatibility

graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/fetchers/BaseConnectionDataFetcher.java, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/fetchers/ConnectionParams.java, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/fetchers/EventConnectionDataFetcher.java, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/fetchers/ProfileConnectionDataFetcher.java, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/fetchers/SegmentConnectionDataFetcher.java, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/fetchers/profile/PropertiesConnectionDataFetcher.java, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/types/output/CDPListConnection.java, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/types/output/CDPPageInfo.java, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/types/output/CDPQuery.java
* Add GraphQL field totalSize in CDPPageInfo
* Enable full-text search for GraphQL queries: findProfiles and findEvents
=> UNOMI-347 improve query results

package/src/main/resources/etc/custom.system.properties, services/src/main/resources/org.apache.unomi.services.cfg
Add an environment variable for Elasticsearch refresh after saving a profile
=> Add an environment variable

package/src/main/resources/etc/custom.system.properties, persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java, persistence-elasticsearch/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, persistence-elasticsearch/core/src/main/resources/org.apache.unomi.persistence.elasticsearch.cfg
Allow a single index for all events (remove monthly index)
=> Allow a single index for all events (remove monthly index)

itests/src/test/java/org/apache/unomi/itests/EventServiceIT.java, plugins/baseplugin/pom.xml, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/SetEventOccurenceCountAction.java, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PastEventConditionESQueryBuilder.java, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PastEventConditionEvaluator.java, plugins/baseplugin/src/main/resources/META-INF/cxs/conditions/pastEventCondition.json, services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
Add option to use fromDate and toDate to pastEvent condition.
The logic of the time range would be an AND between fromDate/toDate/numberOfDays
=> Add toDate and fromDate to pastEventCondition

plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/GeoLocationByPointSessionConditionESQueryBuilder.java, plugins/baseplugin/src/main/resources/META-INF/cxs/conditions/geoLocationByPointSessionCondition.json
…… (#61)
geo location condition: add support for getting location path from parameters and cast integers.
=> Geo location condition: add path and support integers

plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PropertyConditionEvaluator.java, plugins/baseplugin/src/test/java/org/apache/unomi/plugins/baseplugin/conditions/PropertyConditionEvaluatorTest.java
In this implementation I provide a much more complete implementation of the PropertyConditionEvaluator hardcoded tests to cover almost all the cases we used OGNL for. This is also backed by new unit tests.
=> UNOMI-400 More complete hardcoded property accessor implementation

itests/src/test/java/org/apache/unomi/itests/ConditionEvaluatorIT.java, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/BooleanConditionESQueryBuilder.java
=> UNOMI-424 Fix buildQuery for BooleanConditionESQueryBuilder

itests/src/test/java/org/apache/unomi/itests/ContextServletIT.java, itests/src/test/java/org/apache/unomi/itests/TestUtils.java, itests/src/test/resources/personalization.json, services/src/main/java/org/apache/unomi/services/sorts/ScorePersonalizationStrategy.java
Avoid nullpointer when the profile doesnt have any interests
=> UNOMI-414 Fix the ScorePersonalizationStrategy

services/src/main/java/org/apache/unomi/services/impl/definitions/DefinitionsServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/goals/GoalsServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
=> UNOMI-444 redeploy the rules in case they are modified

rest/src/main/java/org/apache/unomi/rest/RestServer.java, rest/src/main/java/org/apache/unomi/rest/RestServerBus.java
…oad server when it's necessary and avoid duplicated features in the bus
=> UNOMI-451 : Use bus service rest server

itests/src/test/resources/testLogin.json, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/AllEventToProfilePropertiesAction.java, samples/login-integration/src/main/resources/META-INF/cxs/rules/exampleLogin.json
https://issues.apache.org/jira/browse/UNOMI-450
=> Dmf 4429 deprecate all event to profile properties action

rest/pom.xml, rest/src/main/java/org/apache/unomi/rest/ClientEndpoint.java, rest/src/main/java/org/apache/unomi/rest/ContextJsonEndpoint.java, rest/src/main/java/org/apache/unomi/rest/EventCollectorResponse.java, rest/src/main/java/org/apache/unomi/rest/EventsCollectorEndpoint.java, rest/src/main/java/org/apache/unomi/utils/Changes.java, rest/src/main/java/org/apache/unomi/utils/HttpUtils.java, rest/src/main/java/org/apache/unomi/utils/ServletCommon.java, wab/src/main/java/org/apache/unomi/web/ClientServlet.java, wab/src/main/resources/OSGI-INF/blueprint/blueprint.xml
=> [UNOMI-449] copy servlet endpoints to jax-rs endpoints.

itests/pom.xml, itests/src/test/java/org/apache/unomi/itests/IncrementInterestsIT.java
=> UNOMI-455 bump es maven plugin and fix IT

wab/src/main/java/org/apache/unomi/web/ClientServlet.java, wab/src/main/java/org/apache/unomi/web/ContextServlet.java, wab/src/main/java/org/apache/unomi/web/EventsCollectorServlet.java
=> UNOMI-449 deprecate servlets

api/pom.xml, api/src/main/java/org/apache/unomi/api/ContextRequest.java, rest/pom.xml, rest/src/main/java/org/apache/unomi/rest/ContextJsonEndpoint.java, rest/src/main/java/org/apache/unomi/rest/EventsCollectorEndpoint.java, rest/src/main/java/org/apache/unomi/rest/RestServer.java, rest/src/main/java/org/apache/unomi/rest/validation/HibernateValidationProviderResolver.java, rest/src/main/java/org/apache/unomi/rest/validation/JAXRSBeanValidationInInterceptorOverride.java
https://issues.apache.org/jira/browse/UNOMI-463
=> handle parameters validation

api/src/main/java/org/apache/unomi/api/Event.java, api/src/main/java/org/apache/unomi/api/Parameter.java, api/src/main/java/org/apache/unomi/api/PartialList.java, api/src/main/java/org/apache/unomi/api/services/ProfileService.java, api/src/main/java/org/apache/unomi/api/services/SegmentService.java, extensions/router/router-api/src/main/java/org/apache/unomi/router/api/services/ImportExportConfigurationService.java, extensions/salesforce-connector/services/src/main/java/org/apache/unomi/sfdc/services/SFDCService.java, extensions/unomi-mailchimp/services/src/main/java/org/apache/unomi/mailchimp/services/MailChimpService.java, persistence-spi/src/main/java/org/apache/unomi/persistence/spi/PersistenceService.java, pom.xml, rest/src/main/java/org/apache/unomi/rest/EventServiceEndpoint.java, rest/src/main/java/org/apache/unomi/rest/PatchServiceEndPoint.java, rest/src/main/java/org/apache/unomi/rest/ProfileServiceEndPoint.java, rest/src/main/java/org/apache/unomi/rest/authentication/RestAuthenticationConfig.java, tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/Migration.java, tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/ConsoleUtils.java, tools/shell-commands/src/main/java/org/apache/unomi/shell/services/UnomiManagementService.java, wab/src/main/java/org/apache/unomi/web/HttpUtils.java
- Add dependencies to fix problem with duplicated dependency with different versions
- Added/fixed existing javadocs on various classes
=> [UNOMI-464] Fix Javadoc generation

api/src/main/java/org/apache/unomi/api/ContextRequest.java, api/src/main/java/org/apache/unomi/api/EventsCollectorRequest.java, api/src/main/java/org/apache/unomi/api/utils/ValidationPattern.java, rest/pom.xml, rest/src/main/java/org/apache/unomi/rest/ContextJsonEndpoint.java, rest/src/main/java/org/apache/unomi/rest/EventsCollectorEndpoint.java
https://issues.apache.org/jira/browse/UNOMI-463
=> UNOMI-463 : add annotations to limit the autorised characters

rest/src/main/java/org/apache/unomi/rest/RestServer.java, rest/src/main/java/org/apache/unomi/rest/exception/ValidationExceptionMapper.java
https://issues.apache.org/jira/browse/UNOMI-463
=> UNOMI-463 : add exception mapping to send error 400

rest/src/main/java/org/apache/unomi/rest/exception/ValidationExceptionMapper.java
https://issues.apache.org/jira/browse/UNOMI-463
=> UNOMI-463 :add minimale log for validation exception

itests/src/test/java/org/apache/unomi/itests/CopyPropertiesActionIT.java, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/CopyPropertiesAction.java
https://issues.apache.org/jira/browse/UNOMI-468
=> UNOMI-468 : consider mapping in copy properties action

package/src/main/resources/etc/custom.system.properties, persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java, persistence-elasticsearch/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, persistence-elasticsearch/core/src/main/resources/org.apache.unomi.persistence.elasticsearch.cfg, persistence-spi/src/main/java/org/apache/unomi/persistence/spi/PersistenceService.java, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/SetEventOccurenceCountAction.java
Jira ticket - https://issues.apache.org/jira/browse/UNOMI-457
Add the ability to control the refresh policy when saving an item
=> UNOMI-457: Expose refresh policy

persistence-spi/src/main/java/org/apache/unomi/persistence/spi/PropertyHelper.java, services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java, services/src/main/java/org/apache/unomi/services/mergers/DefaultPropertyMergeStrategyExecutor.java
[UNOMI-XXX] Pull request title with JIRA reference
**Please** add a meaningful description for your change here
when merging profiles, nested properties overrides.
this pr fixes it by flattening the nested properties before setting it in the target profile
----
Trivial changes like typos do not require a JIRA issue (javadoc, project build changes, small doc …
=> UNOMI-443 - when merging profiles properties flatten nested properties

package/src/main/resources/etc/custom.system.properties, services/src/main/java/org/apache/unomi/services/impl/scheduler/SchedulerServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java, services/src/main/resources/OSGI-INF/blueprint/blueprint.xml, services/src/main/resources/org.apache.unomi.services.cfg, services/src/test/java/org/apache/unomi/services/impl/scheduler/SchedulerServiceImplTest.java
[UNOMI-XXX] Pull request title with JIRA reference
**Please** add a meaningful description for your change here
----
If this is your first contribution, you have to read the [Contribution …
=> UNOMI-484-daily evaluate segments with date expression

rest/src/main/java/org/apache/unomi/rest/exception/RuntimeExceptionMapper.java
see. https://issues.apache.org/jira/browse/UNOMI-488 for details
=> UNOMI-488 : log error in RuntimeExceptionMapper

graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/schema/GraphQLSchemaProvider.java
Fixed generation of GraphQL schema
=> UNOMI-490 Fix schema generation for event types without properties

graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/schema/GraphQLSchemaProvider.java
Fixed by adding a null check and logging the missing event input type
=> UNOMI-495 Fix GraphQLProvider NPE for missing event types

api/src/main/java/org/apache/unomi/api/services/RulesService.java, itests/src/test/java/org/apache/unomi/itests/AllITs.java, itests/src/test/java/org/apache/unomi/itests/BaseIT.java, itests/src/test/java/org/apache/unomi/itests/ConditionBuilder.java, itests/src/test/java/org/apache/unomi/itests/RuleServiceIT.java, package/src/main/resources/etc/custom.system.properties, rest/src/main/java/org/apache/unomi/rest/server/RestServer.java, services/src/main/java/org/apache/unomi/services/impl/ParserHelper.java, services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java, services/src/main/resources/OSGI-INF/blueprint/blueprint.xml, services/src/main/resources/org.apache.unomi.services.cfg
- New optimization for rules: rule conditions are parsed to determine the event types they handle. This is done using a new ParserHelper method that navigates the tree of conditions to resolve which eventTypeCondition are used.
- Settings to deactivate the new optimization in case it causes issues
- Integration tests to validate that the parsing of conditions is behaving as expected
- Performance tests to validate the performance improvement of the optimization
=> UNOMI-188 Rule event type optimization

services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java
https://issues.apache.org/jira/browse/UNOMI-504
=> UNOMI-504 : fix purge profiles

plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PropertyConditionEvaluator.java
This PR is a follow-up to #301 to incorporate requested changes on top of @giladw 's PR
----
If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) 
if you are unsure please ask on the developers list.
To make clear that you …
=> Added condition as per comment in PR #301

itests/src/test/java/org/apache/unomi/itests/ProfileServiceIT.java, plugins/baseplugin/src/main/resources/META-INF/cxs/conditions/profileAliasesPropertyCondition.json, services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java
Delete aliases when a profile is deleted
=> UNOMI-506 Delete aliases when a profile is deleted

extensions/groovy-actions/services/src/main/java/org/apache/unomi/groovy/actions/GroovyActionDispatcher.java, extensions/groovy-actions/services/src/main/java/org/apache/unomi/groovy/actions/listener/GroovyActionListener.java, extensions/groovy-actions/services/src/main/java/org/apache/unomi/groovy/actions/services/GroovyActionsService.java, extensions/groovy-actions/services/src/main/java/org/apache/unomi/groovy/actions/services/impl/GroovyActionsServiceImpl.java, itests/src/test/java/org/apache/unomi/itests/GroovyActionsServiceIT.java, itests/src/test/resources/groovy/MyAction.groovy
https://issues.apache.org/jira/browse/UNOMI-509
=> Improve groovy actions performances

plugins/mail/src/main/resources/org.apache.unomi.plugins.mail.cfg
Fixing value from org.apache.unomi.mail.server.post to org.apache.unomi.mail.server.port. This fix solves an env var config problem because the apache felix is using the env var name to match.
----
- [ X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/UNOMI) filed 
- [ X] Format the pull request title like `[UNOMI-XXX] - Title of the pull request`
- [X ] Provide integration tests for your changes, especially if you are changing the behavior of existing code or adding …
=> [UNOMI-388] - Fixing typo on custom e-mail plugin

extensions/groovy-actions/services/pom.xml, kar/pom.xml, kar/src/main/feature/feature.xml
Related to https://issues.apache.org/jira/browse/UNOMI-508
=> UNOMI-508 : deploy automatically groovy actions extension

manual/src/main/asciidoc/configuration.adoc
This PR contains documentation for Groovy Actions https://issues.apache.org/jira/browse/UNOMI-508
Written jointly with @jsinovassin
=> [UNOMI-508] - Updated the documentation to include Groovy Actions

extensions/groovy-actions/karaf-kar/pom.xml, extensions/groovy-actions/karaf-kar/src/main/feature/feature.xml, itests/pom.xml, kar/src/main/feature/feature.xml, tools/shell-commands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- Removed Groovy actions bundles from Unomi KAR
- Added a feature.xml file for the Groovy Actions feature
- Added the Groovy actions bundles to the unomi:start managed bundles
- Fix a (weird) problem with the dependencies for the integration tests
=> [UNOMI-528] Fix Groovy actions startup

api/src/main/java/org/apache/unomi/api/rules/Rule.java, itests/src/test/java/org/apache/unomi/itests/SegmentIT.java, services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
https://issues.apache.org/jira/browse/UNOMI-527
Covered by integration tests.
=> UNOMI-527 : fix duplicated linkedItems

itests/src/test/java/org/apache/unomi/itests/SegmentIT.java, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PastEventConditionESQueryBuilder.java
https://issues.apache.org/jira/browse/UNOMI-530
Covered by integration test.
=> UNOMI-530 : fix maximumEventCount in past event condition

package/src/main/resources/etc/custom.system.properties, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/MergeProfilesOnPropertyAction.java, rest/src/main/java/org/apache/unomi/rest/endpoints/ContextJsonEndpoint.java, rest/src/main/java/org/apache/unomi/utils/HttpUtils.java, wab/src/main/java/org/apache/unomi/web/ContextServlet.java, wab/src/main/resources/OSGI-INF/blueprint/blueprint.xml, wab/src/main/resources/org.apache.unomi.web.cfg
[UNOMI-XXX] Pull request title with JIRA reference
**Please** add a meaningful description for your change here
----
If this is your first contribution, you have to read the [Contribution …
=> UNOMI-541: handle HttpOnly and Secure option for the profileId cookie

graphql/README.md
Added URL to graphql playground.
To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> [UNOMI-362] Updated Graphql readme as per ticket

persistence-elasticsearch/core/pom.xml, pom.xml
https://issues.apache.org/jira/browse/UNOMI-546
=> UNOMI-546 : update log4j version

rest/src/main/java/org/apache/unomi/rest/endpoints/ContextJsonEndpoint.java
Process properties overrides before any operation in event handler
=> UNOMI-548 : fix properties override

package/pom.xml
[UNOMI-547] - [Allow the unomi package to start offline](https://issues.apache.org/jira/browse/UNOMI-547)
=> [UNOMI-547] - Allow the unomi package to start offline

lifecycle-watcher/src/main/java/org/apache/unomi/lifecycle/BundleWatcher.java, lifecycle-watcher/src/main/resources/OSGI-INF/blueprint/blueprint.xml
https://issues.apache.org/jira/browse/UNOMI-542
=> UNOMI-542 : fix integration tests

itests/src/test/java/org/apache/unomi/itests/RuleServiceIT.java, itests/src/test/java/org/apache/unomi/itests/SegmentIT.java, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/MergeProfilesOnPropertyAction.java
Fixes for failing integration tests before 1.6.x release
=> UNOMI-552 Fixes for failing integration tests before 1.6.x release

api/src/main/java/org/apache/unomi/api/schema/JSONSchemaExtension.java, api/src/main/java/org/apache/unomi/api/schema/json/JSONTypeFactory.java, api/src/main/java/org/apache/unomi/api/services/SchemaService.java, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/schema/GraphQLSchemaProvider.java, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/schema/GraphQLSchemaUpdater.java, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/types/resolvers/CDPEventInterfaceResolver.java, itests/src/test/java/org/apache/unomi/itests/JSONSchemaIT.java, itests/src/test/resources/schemas/extension/extension-test-event-example.json, rest/src/main/java/org/apache/unomi/rest/endpoints/JsonSchemaExtensionEndPoint.java, services/src/main/java/org/apache/unomi/services/impl/events/EventServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/schemas/SchemaServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/schemas/UnomiPropertyTypeKeyword.java, services/src/main/java/org/apache/unomi/services/listener/JsonSchemaListener.java, services/src/main/resources/OSGI-INF/blueprint/blueprint.xml
https://issues.apache.org/jira/browse/UNOMI-561
=> UNOMI-561 : add endpoint to register json extensions

.github/workflows/unomi-ci-build-tests.yml, .gitignore, itests/jacoco-report.sh, itests/pom.xml, itests/src/test/java/org/apache/unomi/itests/BaseIT.java
Now integration test execution produce a code coverage report (available into target/site/jacoco)
This uses Jacoco.
=> UNOMI-565 : add code coverage report

rest/src/main/java/org/apache/unomi/rest/deserializers/ContextRequestDeserializer.java, rest/src/main/java/org/apache/unomi/rest/deserializers/EventsCollectorRequestDeserializer.java
small fixes following UNOMI-562
=> UNOMI-562 :  fix deserializers

itests/src/test/java/org/apache/unomi/itests/JSONSchemaIT.java, itests/src/test/resources/schemas/events/dummy-event-type.json, itests/src/test/resources/schemas/events/float-property-type.json, itests/src/test/resources/schemas/events/test-event-type.json, itests/src/test/resources/schemas/events/test-invalid-name.json, itests/src/test/resources/schemas/events/test-invalid.json, itests/src/test/resources/schemas/extension/extension-test-event-example.json, services/src/main/java/org/apache/unomi/services/impl/schemas/SchemaServiceImpl.java
https://issues.apache.org/jira/browse/UNOMI-563
=> UNOMI-563 : do not allow to save schema with invalid name

persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java, persistence-elasticsearch/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, persistence-elasticsearch/core/src/main/resources/org.apache.unomi.persistence.elasticsearch.cfg
see UNOMI-567
Update to be able to set the log level instead of enabling / disabling logging
=> UNOMI-567 : allow to set log level of rest client

persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java, persistence-elasticsearch/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, persistence-elasticsearch/core/src/main/resources/org.apache.unomi.persistence.elasticsearch.cfg
=> UNOMI-567 : clean up logs - backport of #416

extensions/json-schema/rest/src/main/java/org/apache/unomi/schema/rest/JsonSchemaEndPoint.java, itests/src/test/java/org/apache/unomi/itests/ContextServletIT.java, itests/src/test/java/org/apache/unomi/itests/JSONSchemaIT.java, package/src/main/resources/etc/custom.system.properties
https://issues.apache.org/jira/browse/UNOMI-580
=> UNOMI-580 : add endpoint to get schema + clean

extensions/lists-extension/actions/src/main/java/org/apache/unomi/lists/actions/AddToListsAction.java, extensions/privacy-extension/services/src/main/java/org/apache/unomi/privacy/internal/PrivacyServiceImpl.java, extensions/privacy-extension/services/src/main/resources/OSGI-INF/blueprint/blueprint.xml, graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/actions/CDPSessionAction.java, itests/src/test/java/org/apache/unomi/itests/AllITs.java, itests/src/test/java/org/apache/unomi/itests/SendEventActionIT.java, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/IncrementInterestAction.java, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/MergeProfilesOnPropertyAction.java, plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/SendEventAction.java, rest/src/main/java/org/apache/unomi/rest/endpoints/ContextJsonEndpoint.java, services/src/main/java/org/apache/unomi/services/impl/goals/GoalsServiceImpl.java
https://issues.apache.org/jira/browse/UNOMI-597
=> UNOMI-597: do not persist internal events

tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/impl/MigrationTo200.java, tools/shell-commands/src/main/resources/requestBody/bulkSaveProfileAliases.ndjson
Added the migration which creates a document in `context-profilealias` index based on the profile.
=> UNOMI-505 Study replication of existing profileIDs into new alias index

extensions/json-schema/services/src/main/java/org/apache/unomi/schema/impl/SchemaServiceImpl.java, extensions/json-schema/services/src/main/java/org/apache/unomi/schema/keyword/ScopeKeyword.java, extensions/json-schema/services/src/main/java/org/apache/unomi/schema/keyword/ScopeValidator.java, extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/events/event.json, extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/items/consent/consent.json, extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/items/item.json, extensions/json-schema/services/src/main/resources/OSGI-INF/blueprint/blueprint.xml, itests/src/test/java/org/apache/unomi/itests/BasicIT.java, itests/src/test/java/org/apache/unomi/itests/ContextServletIT.java, itests/src/test/java/org/apache/unomi/itests/InputValidationIT.java, itests/src/test/java/org/apache/unomi/itests/JSONSchemaIT.java, itests/src/test/java/org/apache/unomi/itests/TestUtils.java, itests/src/test/resources/schemas/event-dummy-invalid-4.json, itests/src/test/resources/schemas/event-flattened-valid.json, itests/src/test/resources/schemas/schema-dummy-properties.json, rest/src/main/java/org/apache/unomi/rest/deserializers/ContextRequestDeserializer.java
https://issues.apache.org/jira/browse/UNOMI-598
=> UNOMI-598 : add keyword to validate scopes

package/src/main/resources/etc/custom.system.properties, persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java, services/src/main/resources/OSGI-INF/blueprint/blueprint.xml, services/src/main/resources/org.apache.unomi.services.cfg
https://issues.apache.org/jira/browse/UNOMI-618
=> UNOMI-618 : rename property for more consistency

tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/MigrationScript.java, tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/actions/Migrate.java, tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/impl/MigrationTo150.java, tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/impl/MigrationTo200.java, tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/ConsoleUtils.java, tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/MigrationUtils.java, tools/shell-commands/src/main/resources/META-INF/cxs/migration/migrate-2.0.0-02-scoringPlanReindex.groovy, tools/shell-commands/src/main/resources/requestBody/2.0.0/scoring_index.json
https://issues.apache.org/jira/browse/UNOMI-606
=> UNOMI-606 : create migration for scoring and fix issues

tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/impl/MigrationTo200.java, tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/MigrationUtils.java, tools/shell-commands/src/main/resources/META-INF/cxs/migration/migrate-2.0.0-01-segmentReindex.groovy, tools/shell-commands/src/main/resources/META-INF/cxs/migration/migrate-2.0.0-03-profileReindex.groovy, tools/shell-commands/src/main/resources/requestBody/2.0.0/base_reindex_request.json, tools/shell-commands/src/main/resources/requestBody/2.0.0/migrate_existing_interests.painless, tools/shell-commands/src/main/resources/requestBody/2.0.0/profile_index.json, tools/shell-commands/src/main/resources/requestBody/2.0.0/update_profile_interests.json
https://issues.apache.org/jira/browse/UNOMI-603
=> Unomi 603 migration profiles

rest/src/main/java/org/apache/unomi/rest/deserializers/ContextRequestDeserializer.java, rest/src/main/java/org/apache/unomi/rest/deserializers/EventsCollectorRequestDeserializer.java
https://issues.apache.org/jira/browse/UNOMI-621
=> UNOMI-621 : add error logs when events are invalid

manual/src/main/asciidoc/configuration.adoc
As per feedback in https://issues.apache.org/jira/browse/UNOMI-608
----
- [n/a] Provide integration tests for your changes, especially if you are changing the behavior of existing code or adding
- [n/a] Run `mvn clean install -P integration-tests` to make sure basic checks pass. A more thorough check will be 
To make clear that you license your contribution under the [Apache …
=> [UNOMI-608] Addressed error in Groovy Action documentation (master)

manual/src/main/asciidoc/configuration.adoc
As per feedback in https://issues.apache.org/jira/browse/UNOMI-608
----
- [n/a] Provide integration tests for your changes, especially if you are changing the behavior of existing code or adding
- [n/a] Run `mvn clean install -P integration-tests` to make sure basic checks pass. A more thorough check will be 
To make clear that you license your contribution under the [Apache …
=> [UNOMI-608] Addressed error in Groovy Action documentation (1.6.x branch)

manual/src/main/asciidoc/5-min-quickstart.adoc, manual/src/main/asciidoc/configuration.adoc, manual/src/main/asciidoc/getting-started.adoc, manual/src/main/asciidoc/graphql.adoc, manual/src/main/asciidoc/index.adoc, manual/src/main/asciidoc/jsonSchema/introduction.adoc, manual/src/main/asciidoc/migrations/migrate-1.4-to-1.5.adoc, manual/src/main/asciidoc/migrations/migrate-1.5-to-1.6.adoc, manual/src/main/asciidoc/migrations/migrate-1.6-to-2.0.adoc, manual/src/main/asciidoc/migrations/migrations.adoc, manual/src/main/asciidoc/recipes.adoc, manual/src/main/asciidoc/request-examples.adoc, manual/src/main/asciidoc/whats-new.adoc
This PR still contains a bunch of TODO in the "what's new" section, it will be addressed at a later stage (but before releasing Unomi 2)
----
- [n/a] Provide integration tests for your changes, especially if you are changing the behavior of existing code or adding
- [n/a] Write a pull request description that is detailed enough to understand what the pull request does, how, and why. 
- [n/a] Run `mvn clean install -P …
=> [UNOMI-638] - Updates documentation in preparation for Unomi 2

common/src/test/java/org/apache/unomi/common/DataTableTest.java
Hey 😊
I want to contribute a test.
Curious to hear what you think!
(I wrote this test as part of a research study at TU Delft. [Find out more](https://github.com/lacinoire/lacinoire/blob/main/README.md))
----
-> I believe this to count as a trivial change
-> no new code, but providing tests 🙂
-> passes
Trivial changes like typos do not require a JIRA issue (javadoc, project …
=> [UNOMI-645] - Add test for DataTable$Row.toString and DataTable.toString

extensions/groovy-actions/services/src/main/java/org/apache/unomi/groovy/actions/services/impl/GroovyActionsServiceImpl.java
see https://issues.apache.org/jira/browse/UNOMI-652
=> UNOMI-652 : fix concurrency issue while loading groovy actions

extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/items/page/page.properties.pageInfo.json
see https://issues.apache.org/jira/browse/UNOMI-653
=> UNOMI-653 : add missing properties to pageInfo schema

extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/items/item.json
https://issues.apache.org/jira/browse/UNOMI-654
=> UNOMI-654 : allow empty properties as item field

manual/src/main/asciidoc/migrations/migrate-1.6-to-2.0.adoc
Added more details about the creation of custom migration scripts
=> [UNOMI-669] Added more details on sequencing for the migration in the docs

extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/events/click/click.json, extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/events/form/form.flattenedProperties.fields.json, extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/events/form/form.flattenedProperties.json, extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/events/form/form.json, extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/events/form/form.source.json, extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/events/video/video.json, extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/events/video/video.target.json, extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/events/video/video.target.properties.json
https://issues.apache.org/jira/browse/UNOMI-673
=> UNOMI-673 : add json schema for click, form, video events

NOTICE.template, package/src/main/resources/NOTICE
see https://issues.apache.org/jira/browse/UNOMI-663
=> UNOMI-663 : set year to 2022

src/main/resources/assemblies/source-shared.xml
=> UNOMI-663 : exclude node / node_modules directories

generate-site-and-upload.sh, generate-site.sh
- Update manual generation to generate files for V2.
=> UNOMI-663 V2 release

api/src/main/java/org/apache/unomi/api/ContextResponse.java
https://issues.apache.org/jira/browse/UNOMI-717
=> UNOMI-717 : set back the setter on personalizations in context response

plugins/request/pom.xml, plugins/request/src/main/java/org/apache/unomi/plugins/request/useragent/UserAgentDetectorServiceImpl.java
UNOMI-710 : bump Yauaa to 7.8.0
Note that the cache implementation is made to work with JDK8
=> UNOMI-710 : bump Yauaa to 7.8.0

plugins/request/pom.xml, plugins/request/src/main/java/org/apache/unomi/plugins/request/useragent/UserAgentDetectorServiceImpl.java
Due to Unomi build being broken due to the upgrade we will post pone the upgrade to next version to be able to release unomi 1.7.0
=> UNOMI-710: revert Yauaa 7.8.0 upgrade

extensions/web-tracker/wab/package.json, extensions/web-tracker/wab/src/main/webapp/index.html, extensions/web-tracker/wab/yarn.lock, manual/src/main/asciidoc/tutorial.adoc
https://issues.apache.org/jira/browse/UNOMI-714
=> UNOMI-714 : update unomi-tracker version

manual/src/main/asciidoc/configuration.adoc
https://issues.apache.org/jira/browse/UNOMI-732
=> UNOMI-732 : add example how to use OSGI service in groovy actions

plugins/request/pom.xml
Merge request https://github.com/apache/unomi/pull/557 introduced the need for an unexpected extra `<Import-Package>` setting because of a dependency of Yauaa.
In the just released version of Yauaa this should be fixed.
----
If this is your first …
=> [UNOMI-722]: Update Yauaa to 7.13.0

api/src/main/java/org/apache/unomi/api/services/ClusterService.java, api/src/main/java/org/apache/unomi/api/services/ProfileService.java, itests/src/test/java/org/apache/unomi/itests/ProfileServiceIT.java, package/src/main/resources/etc/custom.system.properties, persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java, persistence-spi/src/main/java/org/apache/unomi/persistence/spi/PersistenceService.java, rest/src/main/java/org/apache/unomi/rest/endpoints/ClusterServiceEndPoint.java, services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java, services/src/main/resources/OSGI-INF/blueprint/blueprint.xml, services/src/main/resources/org.apache.unomi.services.cfg, tools/shell-commands/src/main/resources/requestBody/2.2.0/create_rollover_policy_query.json
https://jira.jahia.org/browse/UNOMI-739
=> Unomi 739 update purge system

extensions/lists-extension/services/src/main/java/org/apache/unomi/services/UserListServiceImpl.java, itests/src/test/java/org/apache/unomi/itests/BaseIT.java, itests/src/test/java/org/apache/unomi/itests/BasicIT.java, itests/src/test/java/org/apache/unomi/itests/ConditionESQueryBuilderIT.java, itests/src/test/java/org/apache/unomi/itests/ContextServletIT.java, itests/src/test/java/org/apache/unomi/itests/PropertiesUpdateActionIT.java, itests/src/test/java/org/apache/unomi/itests/RuleServiceIT.java, itests/src/test/java/org/apache/unomi/itests/SegmentIT.java, itests/src/test/java/org/apache/unomi/itests/graphql/GraphQLEventIT.java, itests/src/test/java/org/apache/unomi/itests/graphql/GraphQLListIT.java, itests/src/test/java/org/apache/unomi/itests/graphql/GraphQLProfileIT.java, itests/src/test/java/org/apache/unomi/itests/graphql/GraphQLSegmentIT.java, itests/src/test/java/org/apache/unomi/itests/graphql/GraphQLSourceIT.java, itests/src/test/java/org/apache/unomi/itests/graphql/GraphQLTopicIT.java, itests/src/test/java/org/apache/unomi/itests/graphql/GraphQLViewIT.java, services/src/main/java/org/apache/unomi/services/impl/AbstractServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/definitions/DefinitionsServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/goals/GoalsServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
https://jira.jahia.org/browse/UNOMI-700
=> UNOMI-700 : specify indices when doing a refresh

extensions/lists-extension/services/src/main/java/org/apache/unomi/services/UserListServiceImpl.java, itests/src/test/java/org/apache/unomi/itests/BaseIT.java, itests/src/test/java/org/apache/unomi/itests/ConditionESQueryBuilderIT.java, itests/src/test/java/org/apache/unomi/itests/ContextServletIT.java, itests/src/test/java/org/apache/unomi/itests/CopyPropertiesActionIT.java, itests/src/test/java/org/apache/unomi/itests/EventServiceIT.java, itests/src/test/java/org/apache/unomi/itests/GroovyActionsServiceIT.java, itests/src/test/java/org/apache/unomi/itests/IncrementPropertyIT.java, itests/src/test/java/org/apache/unomi/itests/PropertiesUpdateActionIT.java, itests/src/test/java/org/apache/unomi/itests/RuleServiceIT.java, itests/src/test/java/org/apache/unomi/itests/SegmentIT.java, services/src/main/java/org/apache/unomi/services/impl/definitions/DefinitionsServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/goals/GoalsServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java, services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java
https://jira.jahia.org/browse/UNOMI-700
=> UNOMI-700 : remove useless refresh

tools/shell-commands/src/main/resources/requestBody/2.0.0/event_migrate.painless
https://issues.apache.org/jira/browse/UNOMI-747
=> UNOMI-747 : add null check in events migration script

itests/src/test/java/org/apache/unomi/itests/GroovyActionsServiceIT.java, itests/src/test/java/org/apache/unomi/itests/SegmentIT.java, services/src/main/java/org/apache/unomi/services/impl/ParserHelper.java
https://issues.apache.org/jira/browse/UNOMI-745
=> UNOMI-745 : check condition to avoid NPE

manual/src/main/asciidoc/jsonSchema/json-schema-api.adoc, manual/src/main/asciidoc/jsonSchema/json-schema-develop.adoc, manual/src/main/asciidoc/jsonSchema/json-schema.adoc
This PR adds documentation entry for the JSON Schema validateEvent endpoint
----
If your pull request is about ~20 lines of code …
=> [UNOMI-763] - validateEvent documentation

extensions/json-schema/rest/src/main/java/org/apache/unomi/schema/rest/JsonSchemaEndPoint.java, extensions/json-schema/services/src/main/java/org/apache/unomi/schema/api/SchemaService.java, extensions/json-schema/services/src/main/java/org/apache/unomi/schema/api/ValidationError.java, extensions/json-schema/services/src/main/java/org/apache/unomi/schema/api/ValidationException.java, extensions/json-schema/services/src/main/java/org/apache/unomi/schema/impl/SchemaServiceImpl.java, itests/src/test/java/org/apache/unomi/itests/JSONSchemaIT.java, manual/src/main/asciidoc/jsonSchema/json-schema-develop.adoc
https://issues.apache.org/jira/browse/UNOMI-775
=> Unomi 775 add validation endpoint

services/src/main/java/org/apache/unomi/services/impl/events/EventServiceImpl.java
https://issues.apache.org/jira/browse/UNOMI-780
=> UNOMI-780 : Allow to use scroll query to get more than 10000 events

services/src/main/java/org/apache/unomi/services/impl/events/EventServiceImpl.java
https://issues.apache.org/jira/browse/UNOMI-780
=> Unomi 780 backport use scroll queries

itests/src/test/java/org/apache/unomi/itests/ContextServletIT.java, rest/src/main/java/org/apache/unomi/rest/endpoints/ContextJsonEndpoint.java
https://issues.apache.org/jira/browse/UNOMI-785
=> Unomi 785 fix npe

rest/src/main/java/org/apache/unomi/rest/service/impl/RestServiceUtilsImpl.java
https://issues.apache.org/jira/browse/UNOMI-792
=> UNOMI-792 : change error log to warn log

package/src/main/resources/etc/custom.system.properties, package/src/main/resources/etc/org.ops4j.pax.logging.cfg
See https://issues.apache.org/jira/browse/UNOMI-796
=> Add config for debug json schema

package/pom.xml
Remove unused management feature. 
see https://issues.apache.org/jira/browse/UNOMI-798
=> UNOMI-798 : remove management feature

manual/src/main/asciidoc/migrations/migrate-1.6-to-2.0.adoc
- Fixed anchor links
- Rewritten some parts to be more precise or easier to understand
- Added environment variable option for JSON schema debugging
=> UNOMI-797 Fixes in migration documentation

.github/workflows/unomi-ci-build-tests.yml, persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java, tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/HttpUtils.java, tools/shell-commands/src/main/resources/META-INF/cxs/migration/migrate-2.0.0-20-scopes.groovy
- add log on metadata items (rules, conditionTypes, etc ..) ES write operations. 
- fix timing issue on scope migration
=> UNOMI-810 : add log on ES operation onto Metadata items.

extensions/json-schema/services/src/main/java/org/apache/unomi/schema/impl/SchemaServiceImpl.java, rest/src/main/java/org/apache/unomi/rest/deserializers/ContextRequestDeserializer.java, rest/src/main/java/org/apache/unomi/rest/deserializers/EventsCollectorRequestDeserializer.java, rest/src/main/java/org/apache/unomi/utils/HttpUtils.java
- Rephrase log message in case of invalid event
- Add debug information on missing json schema or invalid event type
=> UNOMI-811: change log message for invalid event + add debug information on invalid event type.

manual/src/main/asciidoc/graphql-examples.adoc, manual/src/main/asciidoc/index.adoc
Added graphql query examples to GraphQL documentation section
=> UNOMI-576 : Create documentation for GraphQL schema usage

itests/src/test/java/org/apache/unomi/itests/ContextServletIT.java, rest/src/main/java/org/apache/unomi/rest/endpoints/ContextJsonEndpoint.java
https://issues.apache.org/jira/browse/UNOMI-825
Add concealed profile properties.
Set at property type, it prevents a property to be returned when all properties a asked as required properties in a context request. 
The property is readable when accessed directly.
=> UNOMI-825: add concealed profile properties

extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/events/search/search.json, extensions/json-schema/services/src/main/resources/META-INF/cxs/schemas/events/search/search.properties.json
https://issues.apache.org/jira/browse/UNOMI-822
=> UNOMI-822: add search json schema

wab/src/main/java/org/apache/unomi/web/HttpServletRequestForwardWrapper.java
https://issues.apache.org/jira/browse/UNOMI-839
=> UNOMI-839: add charset utf8 in request wrapper

itests/README.md, itests/src/test/java/org/apache/unomi/itests/migration/Migrate16xTo220IT.java, itests/src/test/resources/migration/match_all_login_event_request.json, tools/shell-commands/src/main/resources/META-INF/cxs/migration/migrate-2.4.0-15-viewEventPagePath.groovy, tools/shell-commands/src/main/resources/META-INF/cxs/migration/migrate-2.5.0-10-loginEventScope.groovy, tools/shell-commands/src/main/resources/requestBody/2.0.0/event_migrate.painless, tools/shell-commands/src/main/resources/requestBody/2.5.0/login_event_scope_migrate.painless, tools/shell-commands/src/main/resources/requestBody/2.5.0/scope_update_by_query_request.json
Improve scope migration for login event. 
Add Integration test to cover the migration
=> UNOMI-816 : ensure empty scope are filled properly at migration time

extensions/web-tracker/wab/yarn.lock
UNOMI-840 : update apache unomi tracker to its latest version
=> UNOMI-840 : prepare release 2.5.0

manual/src/main/asciidoc/configuration.adoc
Until UNOMI-847 is fixed, this provides a working example for using Groovy Actions
=> UNOMI-847: Updated the Groovy Action documentation

.github/workflows/codeql-analysis-java.yml, manual/src/main/asciidoc/configuration.adoc
https://issues.apache.org/jira/browse/UNOMI-847
=> UNOMI-847: update documentation to provide a working groovy action

tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/HttpUtils.java, tools/shell-commands/src/main/resources/META-INF/cxs/migration/migrate-2.0.0-20-scopes.groovy, tools/shell-commands/src/main/resources/requestBody/2.0.0/scope_search_by_item_id.json
https://issues.apache.org/jira/browse/UNOMI-862
=> UNOMI-862: fix scope check on migration

api/src/main/java/org/apache/unomi/api/services/RulesService.java, rest/src/main/java/org/apache/unomi/rest/endpoints/RulesServiceEndPoint.java, services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java
https://issues.apache.org/jira/browse/UNOMI-856
=> UNOMI-856: return all rules when calling /rules endpoints

.github/workflows/unomi-ci-build-tests.yml, extensions/healthcheck/src/main/java/org/apache/unomi/healthcheck/HealthCheckConfig.java, extensions/healthcheck/src/main/java/org/apache/unomi/healthcheck/HealthCheckService.java
Fix the OSGI declarative service implementation to allow the config to update the Health check service. 
Covered by integration test.
=> UNOMI-863: set up OSGi DS to allow config update in the HeathCheck service.

package/src/main/resources/etc/custom.system.properties
Jira Ticket: https://issues.apache.org/jira/browse/UNOMI-864
=> UNOMI-864: Remove incorrect space in env variables in custom.system.properties

package/pom.xml
https://issues.apache.org/jira/browse/UNOMI-866
=> UNOMI-866:  Used project.version for log4j-extension version

tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/MigrationUtils.java
https://issues.apache.org/jira/browse/UNOMI-867
=> UNOMI-867: add unique name on refresh

rest/src/main/java/org/apache/unomi/rest/deserializers/EventsCollectorRequestDeserializer.java
https://issues.apache.org/jira/browse/UNOMI-886
=> UNOMI-886: consider profileId from the event collector request
