apache/unomi

- persistence-spi/src/main/java/org/apache/unomi/persistence/spi/PropertyHelper.java
because event updatedProfile is not persisted
> Once per profile notification handled in the mailing action

- persistence-spi/src/main/java/org/apache/unomi/persistence/spi/PropertyHelper.java
- plugins/baseplugin/src/main/resources/META-INF/cxs/conditions/profileSegmentCondition.json
- services/src/main/resources/META-INF/cxs/tags/aggregated.json
because event updatedProfile is not persisted
> Add "aggregated" tag

- wab/src/main/java/org/apache/unomi/web/ContextServlet.java
Two new parameters in the contextServlet : 
- invalidateProfile : The contextServlet will behave as if the profile cookie was not sent (create a new profile and sent the cookie in response)
- invalidateSession : The contextServlet will behave as if there was no session sent with the request
> UNOMI-103 : Add parameter in context servlet to invalidate session or profile

- services/src/main/resources/META-INF/cxs/tags/autocompleted.json
Hello, 
This commit is made to add "autocompleted" tag in Unomi tag list.
This tag will be used to distinct autocompleted properties and is made to Fix Unomi-107
> UNOMI-107 : Add a tag to distinct autocompleted properties.

- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
- persistence-elasticsearch/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- persistence-elasticsearch/core/src/main/resources/org.apache.unomi.persistence.elasticsearch.cfg
Added the aggregateQueryBucketSize config to etc/org.apache.unomi.elasticsearch.cfg with a default value of 5000.
This config allows the user to increase the aggregate query bucket size when 5000 is not sufficient.
> pastEventCondition hardcoded 5000 limit/UNOMI-119

- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
When formatting the date around new year's day, retrieving WEEK_YEAR can
yield next year or previous year as result. We should simply use YEAR.
More details: https://stackoverflow.com/questions/8686331/y-returns-2012-while-y-returns-2011-in-simpledateformat
> UNOMI-152 Fix monthly index New Year's bug

- itests/src/test/java/org/apache/unomi/itests/ProfileImportSurfersIT.java
Now we retrieve property types from DB every 5 seconds
(see 681384714130e49d747c163c5c3ac70774263e59), so we need longer waits
when running integration tests.
> UNOMI-168 Fix property type IT

- package/pom.xml
To achieve this I introduced a dependency of package module on itests
module. It does not build if integration-tests profile is not activated.
> UNOMI-169 Run integration tests before deployment

- extensions/geonames/services/src/main/java/org/apache/unomi/geonames/services/GeonameEntry.java
- extensions/geonames/services/src/main/java/org/apache/unomi/geonames/services/GeonamesServiceImpl.java
The max value holding by this types:
* Integer: 2^31-1 ~= 2147483647
* Long:    2^63-1 ~= 9223372036854775807
So we must use the Long class type to wrap the value of population
> UNOMI-177 update population variable type to Long instead of Integer

- api/src/main/java/org/apache/unomi/api/Event.java
- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ESEventMixIn.java
- wab/src/main/java/org/apache/unomi/web/ContextServlet.java
- wab/src/main/java/org/apache/unomi/web/EventsCollectorServlet.java
Changed the persistence field to be non-transient in the Event class.
Used ESEventMixIn to prevent that value from being saved in ES.  Updated
the Event constructor to accept persistent.
This feature allows the user to pass "persistent": false with their
events if the intent is only to trigger a rule / action downstream.
If "persistent" is not set it defaults to true.
> UNOMI-179 Event Persistence Non-transient

- generate-site-and-upload.sh
- generate-site.sh
- manual/pom.xml
- rest/pom.xml
Use the `generate-site.sh` to generate all the documentation (rest-api-doc, api-javadoc, manual).
The output is located under `target/staging`
> Update generation of documentation script

- services/src/main/java/org/apache/unomi/services/services/EventServiceImpl.java
Escape spaces if exists in the value of thirdparty.provider1.ipAddresses
> UNOMI-220 eliminates leading and trailing spaces into ip value

- docker/Dockerfile
- docker/README.md
- docker/docker-compose.yml
- docker/entrypoint.sh
This pull request simplifies the Unomi evaluation process by adding a few Docker artifacts to make running Unomi locally on Docker quick and easy.
Future work should look at exposing more of the Unomi configuration to Docker. I only setup and tested changing the ES host and port.
> UNOMI-229: Added Docker

- pom.xml
This PR add a profile to run the **owasp** `dependency-check-maven` plugin.
Usage:
- `mvn verify -Powasp` : report generated under `target/dependency-check-report.html`
- `mvn site -Powasp` : report generated under  ̀target/site/dependency-check-report.html`
> [UNOMI-236] Add a profile for OWASP maven plugin

- services/src/main/java/org/apache/unomi/services/services/ProfileServiceImpl.java
Hi,
I've added a small fix for the Jira UNOMI-238.
I declared a new variable on line 1001 because I wasn't able to use `StringUtils. equalsAny` which was introduced with `StringUtils` version 3.5 ([source](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#equalsAny-java.lang.CharSequence-java.lang.CharSequence...-)).
Best regards
Michele
> Fix for Jira UNOMI-238

- services/src/main/java/org/apache/unomi/services/impl/AbstractServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/ParserHelper.java
- services/src/main/java/org/apache/unomi/services/impl/cluster/ClusterServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/cluster/ClusterSystemStatisticsEvent.java
- services/src/main/java/org/apache/unomi/services/impl/cluster/ClusterSystemStatisticsEventHandler.java
- services/src/main/java/org/apache/unomi/services/impl/configsharing/ConfigSharingServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/definitions/DefinitionsServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/events/EventServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/events/ThirdPartyServer.java
- services/src/main/java/org/apache/unomi/services/impl/goals/GoalsServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/lists/UserListServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/patches/PatchServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/personalization/PersonalizationServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/queries/QueryServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/scheduler/SchedulerServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
- services/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Right now we have a bit of a mess in our services implementation sub-project. All the service implementations are in the package:
org.apache.unomi.services.services
I propose that we rename this package to:
org.apache.unomi.services.impl
and that each service gets its own sub-package, for example the RulesServiceImpl would be in:
org.apache.unomi.services.impl.rules
This would make it much easier to activate/deactivate logging per service implementation, because currently it is tricky to get logging activated properly unless using configuration by class. Having it by package would be a lot better.
Utility classes such as ThirdPartyService or the clustering event classes would also be moved with the service sub-package they belong to.
In terms of impact this should minimal, only people …
> UNOMI-250 Refactoring services into seperate Java packages

- manual/src/main/asciidoc/index.adoc
- manual/src/main/asciidoc/queries-and-aggregations.adoc
Currently we don't have documentation for :
- Query count
- Query metrics
- Aggregations
The idea is to add with cURL examples so users can start leveraging this (very) powerful part of Apache Unomi.
This PR adds the new documentation.
Signed-off-by: Serge Huber <shuber@apache.org>
> UNOMI-252 Add documentation for query counts, query metrics and aggregations

- api/src/main/java/org/apache/unomi/api/actions/ActionDispatcher.java
- extensions/groovy-actions/karaf-kar/pom.xml
- extensions/groovy-actions/pom.xml
- extensions/groovy-actions/services/pom.xml
- extensions/groovy-actions/services/src/main/java/org/apache/unomi/services/actions/groovy/GroovyAction.java
- extensions/groovy-actions/services/src/main/java/org/apache/unomi/services/actions/groovy/GroovyActionDispatcher.java
- extensions/groovy-actions/services/src/main/java/org/apache/unomi/services/actions/groovy/GroovyBundleResourceConnector.java
- extensions/groovy-actions/services/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- samples/groovy-actions/pom.xml
- samples/groovy-actions/src/main/resources/META-INF/cxs/actions/testGroovyAction.groovy
- samples/groovy-actions/src/main/resources/META-INF/cxs/actions/testGroovyAction.json
- samples/groovy-actions/src/main/resources/META-INF/cxs/rules/testGroovyActionRule.json
- samples/pom.xml
- services/src/main/java/org/apache/unomi/services/actions/ActionExecutorDispatcher.java
- services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java
- services/src/main/resources/OSGI-INF/blueprint/blueprint.xml
These changes include:
- Make the ActionExecutorDispatcher pluggeable, so that it may delegate to multiple implementations
- Provide an implementation for Groovy
- Provide an sample bundle that uses a Groovy action
Signed-off-by: Serge Huber <shuber@apache.org>
> UNOMI-254 Add Groovy scripting support for actions

- plugins/request/src/main/java/org/apache/unomi/plugins/request/actions/SetRemoteHostInfoAction.java
- plugins/request/src/main/java/org/apache/unomi/plugins/request/useragent/UserAgent.java
- plugins/request/src/main/java/org/apache/unomi/plugins/request/useragent/UserAgentDetectorServiceImpl.java
The useragent service does a great job of grabbing more information than is currently persisted, and this adds the device name (`iPhone 7`) and device brand (`Apple`) to the session information - useful for measurement and specific targeting needs.
> [UNOMI-256] Add device brand and device name to user agent detector

- api/src/main/java/org/apache/unomi/api/PartialList.java
- extensions/lists-extension/services/src/main/java/org/apache/unomi/services/UserListServiceImpl.java
- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/AbstractServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/goals/GoalsServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
- Replaced total hits with count API requests when possible
- For aggregations replaced with a manual sum of all buckets
- Added in the PartialList the relation for the total hits so that users of the API can know if the total size is EQUAL or GREATER_THAN_OR_EQUAL_TO
Signed-off-by: Serge Huber <shuber@apache.org>
> UNOMI-225 ElasticSearch 7 fix for changes in the total hits

- manual/src/main/asciidoc/new-data-model.adoc
- persistence-elasticsearch/core/src/main/resources/META-INF/cxs/mappings/event.json
- persistence-elasticsearch/core/src/main/resources/META-INF/cxs/mappings/profile.json
- persistence-elasticsearch/core/src/main/resources/META-INF/cxs/mappings/propertyType.json
- persistence-elasticsearch/core/src/main/resources/META-INF/cxs/mappings/session.json
- tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/impl/MigrationTo150.java
- tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/HttpUtils.java
These corrections are based on tests with real customer datasets.
Basically the mappings are now first read from the old ElasticSearch 5
indices and then merged with the new mapping definitions included in
Apache Unomi. The result is then used to create the indices properly.
Also, the total mapping fields value is also copied from the ES 5
indices if it exists.
Finally we added an important note in the documentation to mention the
fact that the migration tool only migrates Apache Unomi data. If there is
other data (such as monitoring for example) data in the ElasticSearch 5
cluster it will not be migrated by the tool.
The tool has also been improved to make it possible to stop and continue where it left off in the case of errors, to avoid restarting a migration from scratch. Note that …
> UNOMI-225 ElasticSearch 7 fix issues with mappings when migrating

- docker/docker-compose.yml
UNOMI_ELASTICSEARCH_ADDRESSES was missing in unomi env variables
> fix(docker): add missing env variable

- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PastEventConditionESQueryBuilder.java
Index type is deprecated, also now all types are _doc, this causes past event condition to not function.
> fix(elasticsearch-7): remove type from ids query, type is deprecated

- pom.xml
Hey, 
Karaf references Maven Central via HTTP which stopped working today as per https://support.sonatype.com/hc/en-us/articles/360041287334-Central-501-HTTPS-Required
This is fixed in version 4.2.8
issue is attached here:
https://issues.apache.org/jira/browse/KARAF-6599
> feat(pom.xml): bump karaf version to 4.2.8

- api/src/main/java/org/apache/unomi/api/Profile.java
- extensions/lists-extension/services/src/main/java/org/apache/unomi/services/UserListServiceImpl.java
- extensions/privacy-extension/services/src/main/java/org/apache/unomi/privacy/internal/PrivacyServiceImpl.java
- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
- persistence-spi/src/main/java/org/apache/unomi/persistence/spi/PersistenceService.java
- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/MergeProfilesOnPropertyAction.java
- plugins/mail/src/main/java/org/apache/unomi/plugins/mail/actions/SendMailAction.java
- plugins/pom.xml
- services/src/main/java/org/apache/unomi/services/impl/ParserHelper.java
- services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
- tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/ProfileList.java
- This patch adds the lastUpdated system property to profiles
- Added as a system property to avoid any issues with migration. If it doesn't exist in existing installations it will simply be added the next time a profile is updated.
- Any profile modification (including changing consents, adding new segments or scoring plans) will update the last update date on profiles
- This patch also includes some various minor improvements to logging, that were used while developing this feature
> UNOMI-281 Add lastUpdated system property to Profiles

- rest/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
There is a typo mystake preventing creating index at the first launch.
> UNOMI-288 - Fix: ES Index query correction

- api/src/main/java/org/apache/unomi/api/services/EventService.java
- api/src/main/java/org/apache/unomi/api/services/PrivacyService.java
- api/src/main/java/org/apache/unomi/api/services/ProfileService.java
- extensions/privacy-extension/rest/src/main/java/org/apache/unomi/privacy/rest/PrivacyServiceEndPoint.java
- extensions/privacy-extension/services/src/main/java/org/apache/unomi/privacy/internal/PrivacyServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/events/EventServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java
Added an option to the deleteProfile API (PrivacyService) - when deleting a profile you can now delete also all the profile's sessions and events. I added a new parameter to the deleteProfile API - 
called "purgeAll", when it is set to true the profile's sessions and events are deleted also. The parameter is not required and it's default value is false.
> Unomi 307 enable profile's sessions and events deletion

- api/src/main/java/org/apache/unomi/api/Event.java
- api/src/main/java/org/apache/unomi/api/rules/Rule.java
- api/src/main/java/org/apache/unomi/api/services/EventService.java
- api/src/main/java/org/apache/unomi/api/services/RuleListenerService.java
- itests/src/test/java/org/apache/unomi/itests/AllITs.java
- itests/src/test/java/org/apache/unomi/itests/BasicIT.java
- itests/src/test/java/org/apache/unomi/itests/TestUtils.java
- itests/src/test/java/org/apache/unomi/itests/UpdateEventFromContextServletIT.java
- manual/src/main/asciidoc/datamodel.adoc
- manual/src/main/asciidoc/index.adoc
- manual/src/main/asciidoc/updating-events.adoc
- persistence-elasticsearch/core/src/main/resources/META-INF/cxs/mappings/rule.json
- services/src/main/java/org/apache/unomi/services/impl/events/EventServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java
- wab/src/main/java/org/apache/unomi/web/ServletCommon.java
Hey,
As we understand from the Unomi docs, events are an immutable list of objects that can only be appended too.
As more and more event driven system are being based on tools such as Kafka, we want to have the ability to guard ourselves from receiving duplicate events as consumers usually operates in "at least once" semantics.
We thought that having the ability to pass in the itemId as a parameter to the context servlet would help us in achieving that goal without breaking the current behaviour.
We also want to add the ability to ignore duplicate events in some rules we define, hence we added the `raiseEventOnlyOnce` parameter to the rule creation.
I know that this is modifying `Event`, which is a Unomi core entity.
We were wondering if this is something u might want to consider adding …
> Add the ability to update event by item id

- package/src/main/resources/bin/setenv
- package/src/main/resources/bin/setenv.bat
- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
- Change heap size from 512MB (default) to 2GB
- Catch ElasticsearchStatusException and in the case of an index not found we simply return null, in all other cases we raise the exception
- Fix scroll identifier leak when query returns no results.
> UNOMI-327 Various quality issues

- api/src/main/java/org/apache/unomi/api/Event.java
Fixed by making them persistent by default.
> UNOMI-330 Events non-persistant by default

- manual/src/main/asciidoc/shell-commands.adoc
- tools/shell-dev-commands/src/main/java/org/apache/unomi/shell/commands/EventList.java
- List is now sorted in reverse chronological order
- A new argument makes it possible to filter the list by event type.
> UNOMI-332 Improvements to event-list command

- docker/Dockerfile
- docker/README.md
- docker/docker-compose.yml
- docker/entrypoint.sh
- docker/pom.xml
- extensions/web-tracker/javascript/src/analytics.js-integration-apache-unomi.js
- pom.xml
This PR contains a Maven - Docker integration which brings the following benefits:
- Version is automatically managed by Maven
- Docker-compose is integrated with Maven, making it very easy to build and start a full Unomi environment by just using: `mvn clean install` and then `mvn docker:start` in the Docker sub-project
- Docker push is also possible directly using `mvn docker:push` (it will use the project version as a tag, which should make it also easy to handle releases).
> UNOMI-334 Docker Maven integration

- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/SetEventOccurenceCountAction.java
There was an error when checking if the event's timestamp is in the future. 
When calling Duration.toDays(), negative durations are rounded to 0. This caused future events to be calculated as if they match the "pastEvent" condition
> fix(ContextServletIT) - fix failing integration test

- graphql/graphql-playground/.babelrc
- graphql/graphql-playground/package.json
- graphql/graphql-playground/pom.xml
- graphql/graphql-playground/src/javascript/index.jsx
- graphql/graphql-playground/src/main/webapp/index.css
- graphql/graphql-playground/src/main/webapp/index.html
- graphql/graphql-playground/webpack.config.js
- graphql/pom.xml
- kar/src/main/feature/feature.xml
- package/pom.xml
- wab/src/main/webapp/index.html
Also contains some feature refactoring to make Swagger UI and GraphQL Playground separate Karaf features that could be uninstalled.
> UNOMI-296 Integrate GraphQL Playground

- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/commands/CreateOrUpdateProfilePropertiesCommand.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/providers/CDPDefaultGraphQLProvider.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/types/input/CDPPropertyInput.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/types/input/property/CDPLongPropertyInput.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/types/output/property/CDPLongPropertyType.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/types/output/property/CDPSetPropertyType.java
- itests/src/test/java/org/apache/unomi/itests/SegmentIT.java
- itests/src/test/java/org/apache/unomi/itests/graphql/GraphQLProfilePropertiesIT.java
- itests/src/test/java/org/apache/unomi/itests/graphql/GraphQLSegmentIT.java
- itests/src/test/resources/graphql/profile/create-or-update-profile-properties.json
- itests/src/test/resources/graphql/profile/get-profile-with-new-property.json
NOTE: Java Long (max value 2^63-1) and JavaScript Number ( max value 2^53 - 1) are different, therefore full java long is not safe as stated here https://www.graphql-java.com/documentation/v14/schema/
> UNOMI-354 Add CDP_LongProperty input and output types

- itests/src/test/java/org/apache/unomi/itests/AllITs.java
- itests/src/test/java/org/apache/unomi/itests/EventServiceIT.java
- services/src/main/java/org/apache/unomi/services/impl/events/EventServiceImpl.java
Since adding events with profile ID instead of session ID is now supported, it should be supported also when checking if event has already been raised (otherwise null pointer exception will be thrown)
> Use profile id session is in null to see if event has already been raised

- Jenkinsfile
- Jenkinsfile-jdk11
Add 2 Jenkins file for the new Apache CI:
- https://ci-builds.apache.org/job/Unomi/job/Unomi-jdk8/
- https://ci-builds.apache.org/job/Unomi/job/Unomi-jdk11/
A new job will be automatically created for every PR. 
However, the PR has to rebase to have the Jenkin files to make it work.
> Add Jenkins file

- package/src/main/resources/etc/custom.system.properties
- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
- persistence-elasticsearch/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- persistence-elasticsearch/core/src/main/resources/org.apache.unomi.persistence.elasticsearch.cfg
- persistence-spi/src/main/java/org/apache/unomi/persistence/spi/PersistenceService.java
- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PastEventConditionESQueryBuilder.java
- plugins/baseplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
- services/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Add configurable params for running optimized past event queries:
1. Option to disable partitions for aggregation queries
2. Option to set elasticsearch client socket timeout
3. Option to return error in case of missing docs in aggregation queries
4. Option to set the max http response size in elastic client for aggregation queries
> UNOMI-389: Add optimizations for past event queries

- package/src/main/resources/etc/custom.system.properties
- scripting/src/main/java/org/apache/unomi/scripting/SecureFilteringClassLoader.java
Class java.lang.String was not allowed in SecureFilteringClassLoader. This PR fixes that.
> UNOMI-401 Fix missing base class in SecureFilteringClassLoader

- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/HardcodedPropertyAccessorRegistry.java
- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/accessors/MetadataItemAccessor.java
- plugins/baseplugin/src/test/java/org/apache/unomi/plugins/baseplugin/conditions/HardcodedPropertyAccessorRegistryTest.java
- plugins/baseplugin/src/test/java/org/apache/unomi/plugins/baseplugin/conditions/PropertyConditionEvaluatorTest.java
In this fix was added:
- Proper building of class ancestry to find all the property accessors on a class
- Added unit tests for new ancestry method
- Fix a bug in the MetadataItemAccessor class that was returning null instead of PROPERTY_NOT_FOUND_MARKER
> UNOMI-400 Fix class hierarchy lookup for property condition evaluator

- persistence-elasticsearch/core/src/main/resources/META-INF/cxs/mappings/patch.json
The patch.json is added with this PR to allow to create the indexes in elastic search for the patch index, this taking into account the configuration file.
https://issues.apache.org/jira/browse/UNOMI-410
> UNOMI-410 : add patch template

- manual/src/archives/1.3/asciidoc/samples/twitter-sample.adoc
- manual/src/archives/1.4/asciidoc/samples/twitter-sample.adoc
- manual/src/archives/1.5/asciidoc/samples/twitter-sample.adoc
- manual/src/main/asciidoc/samples/twitter-sample.adoc
In http://unomi.apache.org/manual/1_5_x/index.html#_twitter_sample it is mentioned "You can now go to http://localhost:8181/index.html to test the samples code. ".
The URL should be http://localhost:8181/twitter/index.html.
> Fix URL for testing in twitter sample documentation

- itests/src/test/java/org/apache/unomi/itests/ContextServletIT.java
- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/events/EventTypeRegistryImpl.java
- services/src/main/resources/META-INF/cxs/events/anonymizeProfile.json
- services/src/main/resources/META-INF/cxs/events/articleCompleted.json
- services/src/main/resources/META-INF/cxs/events/form.json
- services/src/main/resources/META-INF/cxs/events/goal.json
- services/src/main/resources/META-INF/cxs/events/identify.json
- services/src/main/resources/META-INF/cxs/events/incrementInterest.json
- services/src/main/resources/META-INF/cxs/events/login.json
- services/src/main/resources/META-INF/cxs/events/modifyConsent.json
- services/src/main/resources/META-INF/cxs/events/profileDeleted.json
- services/src/main/resources/META-INF/cxs/events/ruleFired.json
- services/src/main/resources/META-INF/cxs/events/sessionCreated.json
- services/src/main/resources/META-INF/cxs/events/sessionReassigned.json
- services/src/main/resources/META-INF/cxs/events/updateProperties.json
- services/src/main/resources/META-INF/cxs/events/view.json
- Fix integration tests by adding default event types for all known Unomi event types
- Implement more complete event validation for source and target not just properties
> UNOMI-404 & UNOMI 375 Integration test fix & default event types

- api/pom.xml
- api/src/main/java/org/apache/unomi/api/Event.java
- api/src/main/java/org/apache/unomi/api/Profile.java
- itests/src/test/java/org/apache/unomi/itests/EventServiceIT.java
- itests/src/test/java/org/apache/unomi/itests/ProfileServiceIT.java
- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PropertyConditionEvaluator.java
When querying using "exist" operator in Condition, an existQuery is created and sent to Elasticsearch. According to ES documentation, exist return false the the field in null or empty list - "[]".
The case of an empty list wasn't handled in the eval() method of profile property condition evaluator. Need to return false if the field exist but has a value which is empty list.
> UNOMI-411 Bug fix in profile property condition and add getNestedProperty method

- .github/pull_request_template.md
Currently we have no consistent pull request structure, although we do have processes that we'd like to have contributors follow.
The idea is to use Github's Pull Request Template feature to pre-populate each PR with a list of things to remember to do.
Please let me know what you think of it and any suggestions for improvement you might have.
> UNOMI-431 Add initial proposal for PR template

- graphql/graphql-playground/pom.xml
- graphql/graphql-playground/webpack.config.js
- Remove chunking optimization from Webpack configuration
- Switch Webpack back to development mode.
> UNOMI-438 Fix broken GraphQL Playground

- itests/src/test/java/org/apache/unomi/itests/AllITs.java
- itests/src/test/java/org/apache/unomi/itests/BasicIT.java
- itests/src/test/java/org/apache/unomi/itests/IncrementPropertyIT.java
- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/IncrementPropertyAction.java
- plugins/baseplugin/src/main/resources/META-INF/cxs/actions/incrementProperty.json
- plugins/baseplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- services/src/main/java/org/apache/unomi/services/actions/ActionExecutorDispatcher.java
> UNOMI-446 improve increment action and make it generic

- kar/src/main/feature/feature.xml
- package/pom.xml
- package/src/main/resources/etc/custom.system.properties
- plugins/baseplugin/pom.xml
- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/MergeProfilesOnPropertyAction.java
- plugins/baseplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- plugins/baseplugin/src/main/resources/org.apache.unomi.plugins.base.cfg
JIRA ticket - https://issues.apache.org/jira/browse/UNOMI-428
Added the ability to configure max profiles to merge in a merge action (instead using "-1" hard coded), due to performance issues - when the size is "-1" , the `query()` call generates additional 2 calls - scroll query and the deletion of the scroll.
This is not needed when we know there is a few profiles to merge.
note - since the baseplugin has no cgf file, I wasn't sure what should be done in order to expose it to environment variable (currently it is configurable only from the blueprint file). Would be glad to get your advise about that. Thanks
> UNOMI-428: Configure max profiles to merge instead use max size

- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/MergeProfilesOnPropertyAction.java
Jira task - https://issues.apache.org/jira/browse/UNOMI-440
On merge action, the profile id of the events is updated to be the master profile.
Since the event is saved in ES and right after is updated - it might not return in the query. As a result, the profile id might not be updated.
Added an explicit update.
> UNOMI-440: Add explicit call to update the current profile id of the event

- itests/src/test/java/org/apache/unomi/itests/graphql/GraphQLListIT.java
- tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/impl/MigrationTo200.java
This PR contains the migration from v1.5.0 to v2.0.0 which updates mapping for an index with prefix `context-event`. Adds the `sourceId` field and copies value from the `scope` field to it.
> UNOMI-435 Migrate existing events scope to source

- itests/src/test/java/org/apache/unomi/itests/SegmentIT.java
- persistence-elasticsearch/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> UNOMI-480 Wrong default values for monthlyIndexOverride that changed how indices for events and sessions are split.

- docker/src/main/docker/entrypoint.sh
[UNOMI-479] Docker image will not start if elastic search needs authorization 
Checks if there is authorization needed and adds credentials to url. 
----
If this is your first contribution, you have to read the [Contribution …
> [UNOMI-479] Docker: Checks if there is auth needed for ES and adds credentials to url in entrypoint.sh

- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/providers/CompositeGraphQLFieldVisibility.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/providers/GraphQLFieldVisibilityProvider.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/schema/GraphQLSchemaProvider.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/schema/GraphQLSchemaUpdater.java
- samples/graphql-providers/src/main/java/org/apache/unomi/graphql/providers/sample/CDPProviderSample.java
- samples/graphql-providers/src/main/java/org/apache/unomi/graphql/providers/sample/CDPVisibilityOnlyProvider.java
- Added priority field to graphql visibility provider interface
- Created composite graphql visibility provider to combine multiple visibility providers for graphql schema generation
- Added 2 visibility providers to graphql-providers-sample feature as example
> UNOMI-474 Add priorities to GraphQL field visibility providers

- itests/src/test/java/org/apache/unomi/itests/RuleServiceIT.java
- services/src/main/java/org/apache/unomi/services/impl/ParserHelper.java
- services/src/main/java/org/apache/unomi/services/impl/definitions/DefinitionsServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/events/EventServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/goals/GoalsServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/queries/QueryServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
Here's what was achieved in this PR: 
- Make sure we handle null actions gracefully instead of generating a NPE and blocking loading of further rules
- Add an integration test to test the case of null actions in rule
- Improve logging when rules have null or empty conditions and actions
> UNOMI-492 Make rules engine more robust when some rules are invalid (null actions)

- rest/src/main/java/org/apache/unomi/rest/exception/ValidationExceptionMapper.java
In these changes we simply move the exception stack trace logging from error to debug to avoid generating too much data in the logs.
> UNOMI-494 Change validation exception logging to debug

- services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
This is fixed by adding a dummy profile ID for validation purposes
> UNOMI-493 Fix missing profile ID on Segment integration tests.

- itests/src/test/java/org/apache/unomi/itests/IncrementInterestsIT.java
- itests/src/test/java/org/apache/unomi/itests/IncrementPropertyIT.java
This PR contains the following fixes:
- Proper rule setup with an itemId that was causing the improper teardown of the IncrementInterestsIT
- Proper creation of the pageInfo structure that was causing the NestedNullException on the integration tests
> UNOMI-496 Fix NestedNulllException on increment property/interest integration tests

- itests/src/test/resources/personalization.json
This is fixed by explicitly using lower-level conditions that are equivalent to what the non-existing condition was doing.
> UNOMI-497 Fix reference to non-existant pageViewEventCondition in personalization integration tests

- itests/src/test/java/org/apache/unomi/itests/ProfileServiceIT.java
- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
- persistence-spi/src/main/java/org/apache/unomi/persistence/spi/PersistenceService.java
- The getSetting/setSettings(s) methods on the persistence service could be potentially abused and cause security issues so they are replaced by using OSGi configuration administration property updates
> UNOMI-188 Replace persistence service settings with OSGi config admin properties

- api/src/main/java/org/apache/unomi/api/ContextRequest.java
- api/src/main/java/org/apache/unomi/api/Event.java
- api/src/main/java/org/apache/unomi/api/ProfileAlias.java
- api/src/main/java/org/apache/unomi/api/services/ProfileService.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/fetchers/profile/ProfileDataFetcher.java
- itests/src/test/java/org/apache/unomi/itests/ProfileMergeIT.java
- itests/src/test/java/org/apache/unomi/itests/ProfileServiceIT.java
- persistence-spi/src/main/java/org/apache/unomi/persistence/spi/CustomObjectMapper.java
- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/actions/MergeProfilesOnPropertyAction.java
- rest/src/main/java/org/apache/unomi/rest/endpoints/ContextJsonEndpoint.java
- services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java
This PR introduces aliases on Unomi profiles. Using these aliases we are able to lookup the same profile for different clients.
----
> [UNOMI-445] Implement support for multiple profile IDs on Unomi profiles

- services/src/main/resources/org.apache.unomi.services.cfg
Fix typo in configuration variable value (removing unecessary "env:" part)
> UNOMI-510 : fix typo in service config

- itests/src/test/java/org/apache/unomi/itests/ConditionBuilder.java
- itests/src/test/java/org/apache/unomi/itests/ConditionEvaluatorIT.java
- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PropertyConditionESQueryBuilder.java
- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PropertyConditionEvaluator.java
Add date expression support to isDay / isNotDay property comparison operator. (bonus, fix double property type support)
Covered by unit test.
> UNOMI-523 : add date expression support to isDay / isNotDay property comparison

- api/src/main/java/org/apache/unomi/api/ContextRequest.java
- api/src/main/java/org/apache/unomi/api/ContextResponse.java
- itests/src/test/java/org/apache/unomi/itests/BasicIT.java
- itests/src/test/java/org/apache/unomi/itests/ContextServletIT.java
- itests/src/test/resources/score1.json
- itests/src/test/resources/withRequireScores.json
- itests/src/test/resources/withoutRequireScores.json
- manual/src/main/asciidoc/recipes.adoc
- manual/src/main/asciidoc/request-examples.adoc
- rest/src/main/java/org/apache/unomi/rest/endpoints/ContextJsonEndpoint.java
- Implement new ContextRequest parameter
- Add integration tests that execute with and without the parameter.
- Update documentation to surface the new parameter
> [UNOMI-520] Add possibility to use a "requiresScores" parameter in the ContextRequest

- api/src/main/java/org/apache/unomi/api/utils/ParserHelper.java
- services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java
[UNOMI-532] 
Use same mechanism as in {{ParserHelper}} to not display warning regarding missing rule actions all the time.
> UNOMI-532 : avoid displaying warnings too many times.

- api/src/main/java/org/apache/unomi/api/PersonalizationResult.java
- api/src/main/java/org/apache/unomi/api/PersonalizationStrategy.java
- api/src/main/java/org/apache/unomi/api/services/PersonalizationService.java
- itests/src/test/java/org/apache/unomi/itests/ContextServletIT.java
- itests/src/test/resources/personalization-controlgroup.json
- itests/src/test/resources/personalization.json
- manual/src/main/asciidoc/samples/twitter-sample.adoc
- rest/src/main/java/org/apache/unomi/rest/endpoints/ContextJsonEndpoint.java
- services/src/main/java/org/apache/unomi/services/impl/personalization/ControlGroup.java
- services/src/main/java/org/apache/unomi/services/impl/personalization/PersonalizationServiceImpl.java
- services/src/main/java/org/apache/unomi/services/sorts/FilterPersonalizationStrategy.java
- Personalizations will now store a control group election in the session or in the profile
- Updated documentation for personalization
- Implemented integration tests for control groups
> UNOMI-537 Add control groups to personalizations

- docker/src/main/docker/entrypoint.sh
Updated the entrypoint file to utilise the $UNOMI_ELASTICSEARCH_SSL_ENABLE environment variable.
Tested locally with the env var absent and with values "true" and "false", don't know how to contribute a test for this.
Also: noticed a spelling error, and IDE wouldn't allow me to save the file without the blank line at the end.
> [UNOMI-551] - Utilise SSL in docker entrypoint

- extensions/groovy-actions/karaf-kar/src/main/feature/feature.xml
- lifecycle-watcher/src/main/java/org/apache/unomi/lifecycle/BundleWatcher.java
- Added a dependency to Unomi in Groovy actions feature
- Added a check of bundle states at initialization of Lifecycle Manager, in case it gets started after bundles that are required.
> UNOMI-552 Attempt to fix issue with release:prepare locking Unomi startup.

- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
- persistence-elasticsearch/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- persistence-elasticsearch/core/src/main/resources/org.apache.unomi.persistence.elasticsearch.cfg
Fixes the issue of logs polluted by ES warnings regarding deprecated parameters.
We now change the log level of the RestClient to not display warnings.
If one wants to have them back the configuration parameter `errorLogLevelRestClient` restores the original behavior
> UNOMI-567 : filter out warnings from RestClient

- manual/src/archives/1.5/asciidoc/connectors/connectors.adoc
- manual/src/archives/1.5/asciidoc/datamodel.adoc
- manual/src/archives/1.6/asciidoc/connectors/connectors.adoc
- manual/src/archives/1.6/asciidoc/datamodel.adoc
- manual/src/main/asciidoc/connectors/connectors.adoc
- manual/src/main/asciidoc/datamodel.adoc
- wab/src/main/webapp/index.html
Some descriptions are not precise in online site docs. Should be self-explanatory in the changes.
----
- [n/a] Provide integration tests for your changes, especially if you are changing the behavior of existing code or adding
...oh well, already created one, sorry...
> [UNOMI-564] - Misinformation in some descriptions in online site docs

- manual/src/archives/1.5/asciidoc/building-and-deploying.adoc
- manual/src/archives/1.6/asciidoc/building-and-deploying.adoc
- manual/src/main/asciidoc/building-and-deploying.adoc
A tip in manual for non-English Windows users to avoid a build error due to the asciidoc-maven-plugin error.
Building on a non-English Windows machine, it is very likely to see a build error due to an encoding issue like the following example:
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.6.0:process-asciidoc (output-html) on project unomi-manual: Execution output-html of goal org.asciidoctor:asciidoctor-maven-plugin:1.6.0:process-asciidoc failed: unknown encoding name - MS949 -> [Help 1]
----
Copy the description to the related JIRA …
> [UNOMI-592] - a tip for building on non-English Windows env

- itests/src/test/java/org/apache/unomi/itests/migration/Migrate16xTo200IT.java
- itests/src/test/resources/migration/org.apache.unomi.migration.cfg
- tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/MigrationConfig.java
- tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/actions/Migrate.java
- tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/HttpUtils.java
- tools/shell-commands/src/main/resources/org.apache.unomi.migration.cfg
UNOMI-583 
Now esLogin and esPassword are available to set up ES credentials at migration time.
> UNOMI-583 : add credential support to ES migration data

- persistence-elasticsearch/core/src/main/java/org/apache/unomi/persistence/elasticsearch/ElasticSearchPersistenceServiceImpl.java
https://issues.apache.org/jira/browse/UNOMI-637
> UNOMI-637 : do not create mapping for property type if not necessary

- manual/src/main/asciidoc/configuration.adoc
- manual/src/main/asciidoc/whats-new.adoc
Fixed a few typos in recent updates to the manual.
> UNOMI-656: Fixed typos

- extensions/router/pom.xml
- extensions/router/router-core/pom.xml
- extensions/router/router-karaf-feature/pom.xml
- extensions/router/router-karaf-feature/src/main/feature/feature.xml
- extensions/salesforce-connector/services/pom.xml
- extensions/salesforce-connector/services/src/main/java/org/apache/unomi/sfdc/services/internal/SFDCServiceImpl.java
- graphql/graphql-playground/package.json
- graphql/graphql-playground/src/javascript/index.jsx
- graphql/graphql-playground/yarn.lock
- pom.xml
- Use resolutions to upgrade the needed graphql-playground dependencies
- Fix small warning in GraphQL Playground init
- Add a comment about why commons-email couldn't be upgrade (before of Karaf features using older versions of the javax.mail/mail bundle)
- Upgrade the Kafka client to a minor version that is recommended by dependabot
- Upgrade the Jetty version used by the CometD library in the Salesforce connector
- Upgrade the CometD library in the Salesforce connector
> [UNOMI-659] Fix dependabot warnings

- docker/src/main/docker/Dockerfile
As part of Unomi 2.0, we're updating the base image used by Docker to openjdk 11
To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
> UNOMI-661: Updated base image to openjdk 11

- graphql/karaf-feature/pom.xml
Following a missing signature file while releasing, changing packaging of the feature.
> UNOMI-663 : set graphql feature packaging

- extensions/web-tracker/wab/src/main/webapp/index.html
- manual/src/main/asciidoc/configuration.adoc
- manual/src/main/asciidoc/graphql.adoc
- manual/src/main/asciidoc/index.adoc
- manual/src/main/asciidoc/jsonSchema/json-schema.adoc
- manual/src/main/asciidoc/migrations/migrations.adoc
- manual/src/main/asciidoc/tutorial.adoc
- manual/src/main/asciidoc/web-tracker.adoc
- manual/src/main/asciidoc/whats-new.adoc
- Added profile aliases to what's new section (detailed documentation will be added later in UNOMI-686
- Add new web tracking tutorial that explains how to use the tracker in progressive steps
- Add new tracker reference sections with custom events definition, cookie and session handling and more
- Fix section titles and levels
- Update tracker HTML to align with the new tutorial
> UNOMI-657 New tracker tutorial & reference, profile aliases and more

- docker/pom.xml
- docker/src/main/docker/Dockerfile
- Multi-arch support
- Switch to eclipse-termurin (openjdk image is no longer supported)
> UNOMI-720 Switch base Docker image & add support for multi-arch images

- manual/src/main/asciidoc/5-min-quickstart.adoc
- manual/src/main/asciidoc/building-and-deploying.adoc
- manual/src/main/asciidoc/getting-started.adoc
Updated manual to indicate that JDK 11 is now the minimal recommended version
> [UNOMI-662] Update manual to document JDK 11 as minimal supported version

- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/condition/factories/ProfileConditionFactory.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/condition/parsers/SegmentProfileInterestsConditionParser.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/fetchers/profile/ProfileInterestsDataFetcher.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/types/output/CDPPersona.java
- graphql/cxs-impl/src/main/java/org/apache/unomi/graphql/types/output/CDPProfile.java
- itests/src/test/java/org/apache/unomi/itests/graphql/GraphQLProfilePropertiesIT.java
[UNOMI-617] Update filters to adapt to interests data model changes
In this PR was done:
- Adopted conditions and condition parser for interests
- Adopted ProfileInterestsDataFetcher according to the new data model
- Added the ability to filter interests by viewIds. It was missed
> UNOMI-617: Update filters to adapt to interests data model changes

- manual/src/main/asciidoc/building-and-deploying.adoc
- package/src/main/resources/bin/setenv
- package/src/main/resources/bin/setenv.bat
Remove usage of deprecated parameter to set JVM RAM
> UNOMI-729 : Use default RAM settings

- plugins/request/pom.xml
[UNOMI-722] Update Yauaa to 7.9.0
Update this dependency because of CVE-2022-23496 
---- …
> [UNOMI-722] - Update Yauaa to 7.9.0 (CVE-2022-23496)

- package/src/main/resources/etc/custom.properties
Avoid class not found issue by adding jdk.internal.reflect,jdk.internal.reflect in the framework runtime (jdk9+ issue)
> UNOMI-760 : fix ClassNotFound Exception while executing groovy script

- manual/src/main/asciidoc/jsonSchema/json-schema-develop.adoc
There was a duplicate header (redundant with --user) in the previous version of the doc.
> UNOMI-763: Removed duplicate header

- itests/src/test/java/org/apache/unomi/itests/SegmentIT.java
- services/src/main/java/org/apache/unomi/services/impl/definitions/DefinitionsServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/goals/GoalsServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
https://issues.apache.org/jira/browse/UNOMI-444
> UNOMI-444 redeploy unomi objects in case they are modified (#264)

- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/HardcodedPropertyAccessorRegistry.java
- plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/PropertyConditionEvaluator.java
- plugins/baseplugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
https://issues.apache.org/jira/browse/UNOMI-788
As the property evaluation can fail by design, some warnings were returning false positive information.
> UNOMI-788 : remove missing property warning

- manual/src/main/asciidoc/configuration.adoc
- tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/MigrationUtils.java
[UNOMI-853](https://issues.apache.org/jira/browse/UNOMI-853) **Adapt migration job to use asynchronous mode avoiding timeout and connection lost**
Reindex step during migration has been moved to a async task and check against task completion is done until task finish.  
Update a link to karaf in the doc that was broken.
> [UNOMI-853] Adapt migration job to use asynchronous mode avoiding timeout and connection lost

- extensions/json-schema/services/src/main/java/org/apache/unomi/schema/impl/SchemaServiceImpl.java
- rest/src/main/java/org/apache/unomi/utils/HttpUtils.java
https://issues.apache.org/jira/browse/UNOMI-846
> UNOMI-846: improve log for event validation

- extensions/healthcheck/src/main/java/org/apache/unomi/healthcheck/HealthCheckResponse.java
- extensions/healthcheck/src/main/resources/org.apache.unomi.healthcheck.cfg
- itests/src/test/java/org/apache/unomi/itests/BaseIT.java
- itests/src/test/resources/org.apache.unomi.healthcheck.cfg
- manual/src/main/asciidoc/configuration.adoc
[UNOMI-854](https://issues.apache.org/jira/browse/UNOMI-854) **Add a Healthcheck Endpoint**
Fix HealthCheckResponse JSON format
Configure the extension as disabled by default.
> [UNOMI-854] Add a HealthCheck Endpoint

- tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/MigrationUtils.java
https://issues.apache.org/jira/browse/UNOMI-861
> UNOMI-861: fix task check in migration"

- api/src/main/java/org/apache/unomi/api/ClusterNode.java
- api/src/main/java/org/apache/unomi/api/services/ClusterService.java
- extensions/router/router-core/src/main/java/org/apache/unomi/router/core/context/RouterCamelContext.java
- package/src/main/resources/etc/custom.system.properties
- services/pom.xml
- services/src/main/java/org/apache/unomi/services/impl/cluster/ClusterServiceImpl.java
- services/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- services/src/main/resources/org.apache.unomi.cluster.cfg
Reverts apache/unomi#723
Some dependencies to karaf cellar still present and documentation is not up to date.
Router module still use cluster events to propagate camel route upgrade.
> Revert "UNOMI-877: Replace Karaf Cellar and Hazelcast with PersistenceService for cluster synchronization"

- extensions/groovy-actions/services/src/main/java/org/apache/unomi/groovy/actions/services/impl/GroovyActionsServiceImpl.java
- extensions/json-schema/services/src/main/java/org/apache/unomi/schema/impl/SchemaServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/cluster/ClusterServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/definitions/DefinitionsServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/profiles/ProfileServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/rules/RulesServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/scope/ScopeServiceImpl.java
- services/src/main/java/org/apache/unomi/services/impl/segments/SegmentServiceImpl.java
Replace existing TimerTasks with dedicated TaskExecutor and update codes accordingly.
> [UNOMI-878] Replace TimerTasks with TaskExecutor

- api/pom.xml
- extensions/groovy-actions/services/src/main/java/org/apache/unomi/groovy/actions/ScriptMetadata.java
- extensions/groovy-actions/services/src/main/java/org/apache/unomi/groovy/actions/services/GroovyActionsService.java
- tools/shell-commands/src/main/java/org/apache/unomi/shell/migration/utils/MigrationUtils.java
This PR fixes some issues that prevent javadoc generation.
> UNOMI-906: Fix javadoc tags and new lines.
